/**
 *
 * Generated from https://translate.google.com
 *
 * The languages that Google Translate supports (as of 5/15/16) alongside with their ISO 639-1 codes
 * See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
 */
declare const langs: {
    Automatic: string;
    Afrikaans: string;
    Albanian: string;
    Amharic: string;
    Arabic: string;
    Armenian: string;
    Azerbaijani: string;
    Basque: string;
    Belarusian: string;
    Bengali: string;
    Bosnian: string;
    Bulgarian: string;
    Catalan: string;
    Cebuano: string;
    Chichewa: string;
    "Chinese Simplified": string;
    "Chinese Traditional": string;
    Corsican: string;
    Croatian: string;
    Czech: string;
    Danish: string;
    Dutch: string;
    English: string;
    Esperanto: string;
    Estonian: string;
    Filipino: string;
    Finnish: string;
    French: string;
    Frisian: string;
    Galician: string;
    Georgian: string;
    German: string;
    Greek: string;
    Gujarati: string;
    "Haitian Creole": string;
    Hausa: string;
    Hawaiian: string;
    Hebrew: string;
    Hindi: string;
    Hmong: string;
    Hungarian: string;
    Icelandic: string;
    Igbo: string;
    Indonesian: string;
    Irish: string;
    Italian: string;
    Japanese: string;
    Javanese: string;
    Kannada: string;
    Kazakh: string;
    Khmer: string;
    Korean: string;
    "Kurdish (Kurmanji)": string;
    Kyrgyz: string;
    Lao: string;
    Latin: string;
    Latvian: string;
    Lithuanian: string;
    Luxembourgish: string;
    Macedonian: string;
    Malagasy: string;
    Malay: string;
    Malayalam: string;
    Maltese: string;
    Maori: string;
    Marathi: string;
    Mongolian: string;
    "Myanmar (Burmese)": string;
    Nepali: string;
    Norwegian: string;
    Pashto: string;
    Persian: string;
    Polish: string;
    Portuguese: string;
    Punjabi: string;
    Romanian: string;
    Russian: string;
    Samoan: string;
    "Scots Gaelic": string;
    Serbian: string;
    Sesotho: string;
    Shona: string;
    Sindhi: string;
    Sinhala: string;
    Slovak: string;
    Slovenian: string;
    Somali: string;
    Spanish: string;
    Sundanese: string;
    Swahili: string;
    Swedish: string;
    Tajik: string;
    Tamil: string;
    Telugu: string;
    Thai: string;
    Turkish: string;
    Ukrainian: string;
    Urdu: string;
    Uyghur: string;
    Uzbek: string;
    Vietnamese: string;
    Welsh: string;
    Xhosa: string;
    Yiddish: string;
    Yoruba: string;
    Zulu: string;
};
export declare function isSupport(language: string): boolean;
export declare function getCode(language: string): any;
export declare function getAllLanguage(): string[];
export declare function getAllCode(): any[];
export default langs;
